name: "Docker push"
description: Pushes docker image.
inputs:
  tag:
    description: Name of image to push. It needs to created using other actions (like docker-build).
    required: true
outputs:
  digest:
    description: "Digest of pushed image in sha256 format."
    value: ${{ steps.shell.outputs.digest }}

runs:
  using: "composite"
  steps:
    - name: Push image
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        TAG: ${{ inputs.tag }}
      run: ${ACTION_PATH}/script.sh
      id: shell
